- hosts: agent

  vars:
   - ansible_connection: ssh
   - ansible_ssh_user: azureuser
   - ansible_ssh_pass: _password_
   - ansible_become: yes

  environment:
    JVM_ARGS: -Xms1g -Xmx1g -XX:MaxMetaspaceSize=256m

  tasks:
   - name: user.properties copy
     template: src=/home/apache-jmeter-5.1.1/bin/user.properties dest=/home/apache-jmeter-5.1.1/bin/user.properties

   - name: rmi_keystore.jks copy
     template: src=/home/apache-jmeter-5.1.1/bin/rmi_keystore.jks dest=/home/apache-jmeter-5.1.1/bin/rmi_keystore.jks

   - name: run jmeter-server
     shell: nohup /home/apache-jmeter-5.1.1/bin/jmeter-server < /dev/null > /dev/null 2>&1 &